/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.language.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DotShapeGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ShapeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Shape");
		private final Assignment cShapeAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cShapeAlternatives_0 = (Alternatives)cShapeAssignment.eContents().get(0);
		private final RuleCall cShapePolygonBasedShapeParserRuleCall_0_0 = (RuleCall)cShapeAlternatives_0.eContents().get(0);
		private final RuleCall cShapeRecordBasedShapeParserRuleCall_0_1 = (RuleCall)cShapeAlternatives_0.eContents().get(1);
		
		//Shape:
		//	shape=(PolygonBasedShape | RecordBasedShape);
		public ParserRule getRule() { return rule; }

		//shape=(PolygonBasedShape | RecordBasedShape)
		public Assignment getShapeAssignment() { return cShapeAssignment; }

		//PolygonBasedShape | RecordBasedShape
		public Alternatives getShapeAlternatives_0() { return cShapeAlternatives_0; }

		//PolygonBasedShape
		public RuleCall getShapePolygonBasedShapeParserRuleCall_0_0() { return cShapePolygonBasedShapeParserRuleCall_0_0; }

		//RecordBasedShape
		public RuleCall getShapeRecordBasedShapeParserRuleCall_0_1() { return cShapeRecordBasedShapeParserRuleCall_0_1; }
	}

	public class PolygonBasedShapeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PolygonBasedShape");
		private final Assignment cShapeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cShapePolygonBasedNodeShapeEnumRuleCall_0 = (RuleCall)cShapeAssignment.eContents().get(0);
		
		//PolygonBasedShape:
		//	shape=PolygonBasedNodeShape;
		public ParserRule getRule() { return rule; }

		//shape=PolygonBasedNodeShape
		public Assignment getShapeAssignment() { return cShapeAssignment; }

		//PolygonBasedNodeShape
		public RuleCall getShapePolygonBasedNodeShapeEnumRuleCall_0() { return cShapePolygonBasedNodeShapeEnumRuleCall_0; }
	}

	public class RecordBasedShapeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RecordBasedShape");
		private final Assignment cShapeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cShapeRecordBasedNodeShapeEnumRuleCall_0 = (RuleCall)cShapeAssignment.eContents().get(0);
		
		//RecordBasedShape:
		//	shape=RecordBasedNodeShape;
		public ParserRule getRule() { return rule; }

		//shape=RecordBasedNodeShape
		public Assignment getShapeAssignment() { return cShapeAssignment; }

		//RecordBasedNodeShape
		public RuleCall getShapeRecordBasedNodeShapeEnumRuleCall_0() { return cShapeRecordBasedNodeShapeEnumRuleCall_0; }
	}
	
	
	public class PolygonBasedNodeShapeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "PolygonBasedNodeShape");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBoxEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBoxBoxKeyword_0_0 = (Keyword)cBoxEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPolygonEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPolygonPolygonKeyword_1_0 = (Keyword)cPolygonEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEllipseEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cEllipseEllipseKeyword_2_0 = (Keyword)cEllipseEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cOvalEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cOvalOvalKeyword_3_0 = (Keyword)cOvalEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCircleEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCircleCircleKeyword_4_0 = (Keyword)cCircleEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPointEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPointPointKeyword_5_0 = (Keyword)cPointEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cEggEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cEggEggKeyword_6_0 = (Keyword)cEggEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cTriangleEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cTriangleTriangleKeyword_7_0 = (Keyword)cTriangleEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cPlaintextEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cPlaintextPlaintextKeyword_8_0 = (Keyword)cPlaintextEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cPlainEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cPlainPlainKeyword_9_0 = (Keyword)cPlainEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cDiamondEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cDiamondDiamondKeyword_10_0 = (Keyword)cDiamondEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cTrapeziumEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cTrapeziumTrapeziumKeyword_11_0 = (Keyword)cTrapeziumEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cParallelogramEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cParallelogramParallelogramKeyword_12_0 = (Keyword)cParallelogramEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cHouseEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cHouseHouseKeyword_13_0 = (Keyword)cHouseEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cPentagonEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cPentagonPentagonKeyword_14_0 = (Keyword)cPentagonEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cHexagonEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cHexagonHexagonKeyword_15_0 = (Keyword)cHexagonEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cSeptagonEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cSeptagonSeptagonKeyword_16_0 = (Keyword)cSeptagonEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cOctagonEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cOctagonOctagonKeyword_17_0 = (Keyword)cOctagonEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cDoublecircleEnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cDoublecircleDoublecircleKeyword_18_0 = (Keyword)cDoublecircleEnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleoctagonEnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cDoubleoctagonDoubleoctagonKeyword_19_0 = (Keyword)cDoubleoctagonEnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cTripleoctagonEnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cTripleoctagonTripleoctagonKeyword_20_0 = (Keyword)cTripleoctagonEnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cInvtriangleEnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cInvtriangleInvtriangleKeyword_21_0 = (Keyword)cInvtriangleEnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cInvtrapeziumEnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cInvtrapeziumInvtrapeziumKeyword_22_0 = (Keyword)cInvtrapeziumEnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cInvhouseEnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cInvhouseInvhouseKeyword_23_0 = (Keyword)cInvhouseEnumLiteralDeclaration_23.eContents().get(0);
		private final EnumLiteralDeclaration cMdiamondEnumLiteralDeclaration_24 = (EnumLiteralDeclaration)cAlternatives.eContents().get(24);
		private final Keyword cMdiamondMdiamondKeyword_24_0 = (Keyword)cMdiamondEnumLiteralDeclaration_24.eContents().get(0);
		private final EnumLiteralDeclaration cMsquareEnumLiteralDeclaration_25 = (EnumLiteralDeclaration)cAlternatives.eContents().get(25);
		private final Keyword cMsquareMsquareKeyword_25_0 = (Keyword)cMsquareEnumLiteralDeclaration_25.eContents().get(0);
		private final EnumLiteralDeclaration cMcircleEnumLiteralDeclaration_26 = (EnumLiteralDeclaration)cAlternatives.eContents().get(26);
		private final Keyword cMcircleMcircleKeyword_26_0 = (Keyword)cMcircleEnumLiteralDeclaration_26.eContents().get(0);
		private final EnumLiteralDeclaration cRectEnumLiteralDeclaration_27 = (EnumLiteralDeclaration)cAlternatives.eContents().get(27);
		private final Keyword cRectRectKeyword_27_0 = (Keyword)cRectEnumLiteralDeclaration_27.eContents().get(0);
		private final EnumLiteralDeclaration cRectangleEnumLiteralDeclaration_28 = (EnumLiteralDeclaration)cAlternatives.eContents().get(28);
		private final Keyword cRectangleRectangleKeyword_28_0 = (Keyword)cRectangleEnumLiteralDeclaration_28.eContents().get(0);
		private final EnumLiteralDeclaration cSquareEnumLiteralDeclaration_29 = (EnumLiteralDeclaration)cAlternatives.eContents().get(29);
		private final Keyword cSquareSquareKeyword_29_0 = (Keyword)cSquareEnumLiteralDeclaration_29.eContents().get(0);
		private final EnumLiteralDeclaration cStarEnumLiteralDeclaration_30 = (EnumLiteralDeclaration)cAlternatives.eContents().get(30);
		private final Keyword cStarStarKeyword_30_0 = (Keyword)cStarEnumLiteralDeclaration_30.eContents().get(0);
		private final EnumLiteralDeclaration cNoneEnumLiteralDeclaration_31 = (EnumLiteralDeclaration)cAlternatives.eContents().get(31);
		private final Keyword cNoneNoneKeyword_31_0 = (Keyword)cNoneEnumLiteralDeclaration_31.eContents().get(0);
		private final EnumLiteralDeclaration cUnderlineEnumLiteralDeclaration_32 = (EnumLiteralDeclaration)cAlternatives.eContents().get(32);
		private final Keyword cUnderlineUnderlineKeyword_32_0 = (Keyword)cUnderlineEnumLiteralDeclaration_32.eContents().get(0);
		private final EnumLiteralDeclaration cCylinderEnumLiteralDeclaration_33 = (EnumLiteralDeclaration)cAlternatives.eContents().get(33);
		private final Keyword cCylinderCylinderKeyword_33_0 = (Keyword)cCylinderEnumLiteralDeclaration_33.eContents().get(0);
		private final EnumLiteralDeclaration cNoteEnumLiteralDeclaration_34 = (EnumLiteralDeclaration)cAlternatives.eContents().get(34);
		private final Keyword cNoteNoteKeyword_34_0 = (Keyword)cNoteEnumLiteralDeclaration_34.eContents().get(0);
		private final EnumLiteralDeclaration cTabEnumLiteralDeclaration_35 = (EnumLiteralDeclaration)cAlternatives.eContents().get(35);
		private final Keyword cTabTabKeyword_35_0 = (Keyword)cTabEnumLiteralDeclaration_35.eContents().get(0);
		private final EnumLiteralDeclaration cFolderEnumLiteralDeclaration_36 = (EnumLiteralDeclaration)cAlternatives.eContents().get(36);
		private final Keyword cFolderFolderKeyword_36_0 = (Keyword)cFolderEnumLiteralDeclaration_36.eContents().get(0);
		private final EnumLiteralDeclaration cBox3dEnumLiteralDeclaration_37 = (EnumLiteralDeclaration)cAlternatives.eContents().get(37);
		private final Keyword cBox3dBox3dKeyword_37_0 = (Keyword)cBox3dEnumLiteralDeclaration_37.eContents().get(0);
		private final EnumLiteralDeclaration cComponentEnumLiteralDeclaration_38 = (EnumLiteralDeclaration)cAlternatives.eContents().get(38);
		private final Keyword cComponentComponentKeyword_38_0 = (Keyword)cComponentEnumLiteralDeclaration_38.eContents().get(0);
		private final EnumLiteralDeclaration cPromoterEnumLiteralDeclaration_39 = (EnumLiteralDeclaration)cAlternatives.eContents().get(39);
		private final Keyword cPromoterPromoterKeyword_39_0 = (Keyword)cPromoterEnumLiteralDeclaration_39.eContents().get(0);
		private final EnumLiteralDeclaration cCdsEnumLiteralDeclaration_40 = (EnumLiteralDeclaration)cAlternatives.eContents().get(40);
		private final Keyword cCdsCdsKeyword_40_0 = (Keyword)cCdsEnumLiteralDeclaration_40.eContents().get(0);
		private final EnumLiteralDeclaration cTerminatorEnumLiteralDeclaration_41 = (EnumLiteralDeclaration)cAlternatives.eContents().get(41);
		private final Keyword cTerminatorTerminatorKeyword_41_0 = (Keyword)cTerminatorEnumLiteralDeclaration_41.eContents().get(0);
		private final EnumLiteralDeclaration cUtrEnumLiteralDeclaration_42 = (EnumLiteralDeclaration)cAlternatives.eContents().get(42);
		private final Keyword cUtrUtrKeyword_42_0 = (Keyword)cUtrEnumLiteralDeclaration_42.eContents().get(0);
		private final EnumLiteralDeclaration cPrimersiteEnumLiteralDeclaration_43 = (EnumLiteralDeclaration)cAlternatives.eContents().get(43);
		private final Keyword cPrimersitePrimersiteKeyword_43_0 = (Keyword)cPrimersiteEnumLiteralDeclaration_43.eContents().get(0);
		private final EnumLiteralDeclaration cRestrictionsiteEnumLiteralDeclaration_44 = (EnumLiteralDeclaration)cAlternatives.eContents().get(44);
		private final Keyword cRestrictionsiteRestrictionsiteKeyword_44_0 = (Keyword)cRestrictionsiteEnumLiteralDeclaration_44.eContents().get(0);
		private final EnumLiteralDeclaration cFivepoverhangEnumLiteralDeclaration_45 = (EnumLiteralDeclaration)cAlternatives.eContents().get(45);
		private final Keyword cFivepoverhangFivepoverhangKeyword_45_0 = (Keyword)cFivepoverhangEnumLiteralDeclaration_45.eContents().get(0);
		private final EnumLiteralDeclaration cThreepoverhangEnumLiteralDeclaration_46 = (EnumLiteralDeclaration)cAlternatives.eContents().get(46);
		private final Keyword cThreepoverhangThreepoverhangKeyword_46_0 = (Keyword)cThreepoverhangEnumLiteralDeclaration_46.eContents().get(0);
		private final EnumLiteralDeclaration cNoverhangEnumLiteralDeclaration_47 = (EnumLiteralDeclaration)cAlternatives.eContents().get(47);
		private final Keyword cNoverhangNoverhangKeyword_47_0 = (Keyword)cNoverhangEnumLiteralDeclaration_47.eContents().get(0);
		private final EnumLiteralDeclaration cAssemblyEnumLiteralDeclaration_48 = (EnumLiteralDeclaration)cAlternatives.eContents().get(48);
		private final Keyword cAssemblyAssemblyKeyword_48_0 = (Keyword)cAssemblyEnumLiteralDeclaration_48.eContents().get(0);
		private final EnumLiteralDeclaration cSignatureEnumLiteralDeclaration_49 = (EnumLiteralDeclaration)cAlternatives.eContents().get(49);
		private final Keyword cSignatureSignatureKeyword_49_0 = (Keyword)cSignatureEnumLiteralDeclaration_49.eContents().get(0);
		private final EnumLiteralDeclaration cInsulatorEnumLiteralDeclaration_50 = (EnumLiteralDeclaration)cAlternatives.eContents().get(50);
		private final Keyword cInsulatorInsulatorKeyword_50_0 = (Keyword)cInsulatorEnumLiteralDeclaration_50.eContents().get(0);
		private final EnumLiteralDeclaration cRibositeEnumLiteralDeclaration_51 = (EnumLiteralDeclaration)cAlternatives.eContents().get(51);
		private final Keyword cRibositeRibositeKeyword_51_0 = (Keyword)cRibositeEnumLiteralDeclaration_51.eContents().get(0);
		private final EnumLiteralDeclaration cRnastabEnumLiteralDeclaration_52 = (EnumLiteralDeclaration)cAlternatives.eContents().get(52);
		private final Keyword cRnastabRnastabKeyword_52_0 = (Keyword)cRnastabEnumLiteralDeclaration_52.eContents().get(0);
		private final EnumLiteralDeclaration cProteasesiteEnumLiteralDeclaration_53 = (EnumLiteralDeclaration)cAlternatives.eContents().get(53);
		private final Keyword cProteasesiteProteasesiteKeyword_53_0 = (Keyword)cProteasesiteEnumLiteralDeclaration_53.eContents().get(0);
		private final EnumLiteralDeclaration cProteinstabEnumLiteralDeclaration_54 = (EnumLiteralDeclaration)cAlternatives.eContents().get(54);
		private final Keyword cProteinstabProteinstabKeyword_54_0 = (Keyword)cProteinstabEnumLiteralDeclaration_54.eContents().get(0);
		private final EnumLiteralDeclaration cRpromoterEnumLiteralDeclaration_55 = (EnumLiteralDeclaration)cAlternatives.eContents().get(55);
		private final Keyword cRpromoterRpromoterKeyword_55_0 = (Keyword)cRpromoterEnumLiteralDeclaration_55.eContents().get(0);
		private final EnumLiteralDeclaration cRarrowEnumLiteralDeclaration_56 = (EnumLiteralDeclaration)cAlternatives.eContents().get(56);
		private final Keyword cRarrowRarrowKeyword_56_0 = (Keyword)cRarrowEnumLiteralDeclaration_56.eContents().get(0);
		private final EnumLiteralDeclaration cLarrowEnumLiteralDeclaration_57 = (EnumLiteralDeclaration)cAlternatives.eContents().get(57);
		private final Keyword cLarrowLarrowKeyword_57_0 = (Keyword)cLarrowEnumLiteralDeclaration_57.eContents().get(0);
		private final EnumLiteralDeclaration cLpromoterEnumLiteralDeclaration_58 = (EnumLiteralDeclaration)cAlternatives.eContents().get(58);
		private final Keyword cLpromoterLpromoterKeyword_58_0 = (Keyword)cLpromoterEnumLiteralDeclaration_58.eContents().get(0);
		
		//enum PolygonBasedNodeShape:
		//	box | polygon | ellipse | oval | circle | point | egg | triangle | plaintext | plain | diamond | trapezium |
		//	parallelogram | house | pentagon | hexagon | septagon | octagon | doublecircle | doubleoctagon | tripleoctagon |
		//	invtriangle | invtrapezium | invhouse | Mdiamond | Msquare | Mcircle | rect | rectangle | square | star | none |
		//	underline | cylinder | note | tab | folder | box3d | component | promoter | cds | terminator | utr | primersite |
		//	restrictionsite | fivepoverhang | threepoverhang | noverhang | assembly | signature | insulator | ribosite | rnastab |
		//	proteasesite | proteinstab | rpromoter | rarrow | larrow | lpromoter;
		public EnumRule getRule() { return rule; }

		//box | polygon | ellipse | oval | circle | point | egg | triangle | plaintext | plain | diamond | trapezium |
		//parallelogram | house | pentagon | hexagon | septagon | octagon | doublecircle | doubleoctagon | tripleoctagon |
		//invtriangle | invtrapezium | invhouse | Mdiamond | Msquare | Mcircle | rect | rectangle | square | star | none |
		//underline | cylinder | note | tab | folder | box3d | component | promoter | cds | terminator | utr | primersite |
		//restrictionsite | fivepoverhang | threepoverhang | noverhang | assembly | signature | insulator | ribosite | rnastab |
		//proteasesite | proteinstab | rpromoter | rarrow | larrow | lpromoter
		public Alternatives getAlternatives() { return cAlternatives; }

		//box
		public EnumLiteralDeclaration getBoxEnumLiteralDeclaration_0() { return cBoxEnumLiteralDeclaration_0; }

		//"box"
		public Keyword getBoxBoxKeyword_0_0() { return cBoxBoxKeyword_0_0; }

		//polygon
		public EnumLiteralDeclaration getPolygonEnumLiteralDeclaration_1() { return cPolygonEnumLiteralDeclaration_1; }

		//"polygon"
		public Keyword getPolygonPolygonKeyword_1_0() { return cPolygonPolygonKeyword_1_0; }

		//ellipse
		public EnumLiteralDeclaration getEllipseEnumLiteralDeclaration_2() { return cEllipseEnumLiteralDeclaration_2; }

		//"ellipse"
		public Keyword getEllipseEllipseKeyword_2_0() { return cEllipseEllipseKeyword_2_0; }

		//oval
		public EnumLiteralDeclaration getOvalEnumLiteralDeclaration_3() { return cOvalEnumLiteralDeclaration_3; }

		//"oval"
		public Keyword getOvalOvalKeyword_3_0() { return cOvalOvalKeyword_3_0; }

		//circle
		public EnumLiteralDeclaration getCircleEnumLiteralDeclaration_4() { return cCircleEnumLiteralDeclaration_4; }

		//"circle"
		public Keyword getCircleCircleKeyword_4_0() { return cCircleCircleKeyword_4_0; }

		//point
		public EnumLiteralDeclaration getPointEnumLiteralDeclaration_5() { return cPointEnumLiteralDeclaration_5; }

		//"point"
		public Keyword getPointPointKeyword_5_0() { return cPointPointKeyword_5_0; }

		//egg
		public EnumLiteralDeclaration getEggEnumLiteralDeclaration_6() { return cEggEnumLiteralDeclaration_6; }

		//"egg"
		public Keyword getEggEggKeyword_6_0() { return cEggEggKeyword_6_0; }

		//triangle
		public EnumLiteralDeclaration getTriangleEnumLiteralDeclaration_7() { return cTriangleEnumLiteralDeclaration_7; }

		//"triangle"
		public Keyword getTriangleTriangleKeyword_7_0() { return cTriangleTriangleKeyword_7_0; }

		//plaintext
		public EnumLiteralDeclaration getPlaintextEnumLiteralDeclaration_8() { return cPlaintextEnumLiteralDeclaration_8; }

		//"plaintext"
		public Keyword getPlaintextPlaintextKeyword_8_0() { return cPlaintextPlaintextKeyword_8_0; }

		//plain
		public EnumLiteralDeclaration getPlainEnumLiteralDeclaration_9() { return cPlainEnumLiteralDeclaration_9; }

		//"plain"
		public Keyword getPlainPlainKeyword_9_0() { return cPlainPlainKeyword_9_0; }

		//diamond
		public EnumLiteralDeclaration getDiamondEnumLiteralDeclaration_10() { return cDiamondEnumLiteralDeclaration_10; }

		//"diamond"
		public Keyword getDiamondDiamondKeyword_10_0() { return cDiamondDiamondKeyword_10_0; }

		//trapezium
		public EnumLiteralDeclaration getTrapeziumEnumLiteralDeclaration_11() { return cTrapeziumEnumLiteralDeclaration_11; }

		//"trapezium"
		public Keyword getTrapeziumTrapeziumKeyword_11_0() { return cTrapeziumTrapeziumKeyword_11_0; }

		//parallelogram
		public EnumLiteralDeclaration getParallelogramEnumLiteralDeclaration_12() { return cParallelogramEnumLiteralDeclaration_12; }

		//"parallelogram"
		public Keyword getParallelogramParallelogramKeyword_12_0() { return cParallelogramParallelogramKeyword_12_0; }

		//house
		public EnumLiteralDeclaration getHouseEnumLiteralDeclaration_13() { return cHouseEnumLiteralDeclaration_13; }

		//"house"
		public Keyword getHouseHouseKeyword_13_0() { return cHouseHouseKeyword_13_0; }

		//pentagon
		public EnumLiteralDeclaration getPentagonEnumLiteralDeclaration_14() { return cPentagonEnumLiteralDeclaration_14; }

		//"pentagon"
		public Keyword getPentagonPentagonKeyword_14_0() { return cPentagonPentagonKeyword_14_0; }

		//hexagon
		public EnumLiteralDeclaration getHexagonEnumLiteralDeclaration_15() { return cHexagonEnumLiteralDeclaration_15; }

		//"hexagon"
		public Keyword getHexagonHexagonKeyword_15_0() { return cHexagonHexagonKeyword_15_0; }

		//septagon
		public EnumLiteralDeclaration getSeptagonEnumLiteralDeclaration_16() { return cSeptagonEnumLiteralDeclaration_16; }

		//"septagon"
		public Keyword getSeptagonSeptagonKeyword_16_0() { return cSeptagonSeptagonKeyword_16_0; }

		//octagon
		public EnumLiteralDeclaration getOctagonEnumLiteralDeclaration_17() { return cOctagonEnumLiteralDeclaration_17; }

		//"octagon"
		public Keyword getOctagonOctagonKeyword_17_0() { return cOctagonOctagonKeyword_17_0; }

		//doublecircle
		public EnumLiteralDeclaration getDoublecircleEnumLiteralDeclaration_18() { return cDoublecircleEnumLiteralDeclaration_18; }

		//"doublecircle"
		public Keyword getDoublecircleDoublecircleKeyword_18_0() { return cDoublecircleDoublecircleKeyword_18_0; }

		//doubleoctagon
		public EnumLiteralDeclaration getDoubleoctagonEnumLiteralDeclaration_19() { return cDoubleoctagonEnumLiteralDeclaration_19; }

		//"doubleoctagon"
		public Keyword getDoubleoctagonDoubleoctagonKeyword_19_0() { return cDoubleoctagonDoubleoctagonKeyword_19_0; }

		//tripleoctagon
		public EnumLiteralDeclaration getTripleoctagonEnumLiteralDeclaration_20() { return cTripleoctagonEnumLiteralDeclaration_20; }

		//"tripleoctagon"
		public Keyword getTripleoctagonTripleoctagonKeyword_20_0() { return cTripleoctagonTripleoctagonKeyword_20_0; }

		//invtriangle
		public EnumLiteralDeclaration getInvtriangleEnumLiteralDeclaration_21() { return cInvtriangleEnumLiteralDeclaration_21; }

		//"invtriangle"
		public Keyword getInvtriangleInvtriangleKeyword_21_0() { return cInvtriangleInvtriangleKeyword_21_0; }

		//invtrapezium
		public EnumLiteralDeclaration getInvtrapeziumEnumLiteralDeclaration_22() { return cInvtrapeziumEnumLiteralDeclaration_22; }

		//"invtrapezium"
		public Keyword getInvtrapeziumInvtrapeziumKeyword_22_0() { return cInvtrapeziumInvtrapeziumKeyword_22_0; }

		//invhouse
		public EnumLiteralDeclaration getInvhouseEnumLiteralDeclaration_23() { return cInvhouseEnumLiteralDeclaration_23; }

		//"invhouse"
		public Keyword getInvhouseInvhouseKeyword_23_0() { return cInvhouseInvhouseKeyword_23_0; }

		//Mdiamond
		public EnumLiteralDeclaration getMdiamondEnumLiteralDeclaration_24() { return cMdiamondEnumLiteralDeclaration_24; }

		//"Mdiamond"
		public Keyword getMdiamondMdiamondKeyword_24_0() { return cMdiamondMdiamondKeyword_24_0; }

		//Msquare
		public EnumLiteralDeclaration getMsquareEnumLiteralDeclaration_25() { return cMsquareEnumLiteralDeclaration_25; }

		//"Msquare"
		public Keyword getMsquareMsquareKeyword_25_0() { return cMsquareMsquareKeyword_25_0; }

		//Mcircle
		public EnumLiteralDeclaration getMcircleEnumLiteralDeclaration_26() { return cMcircleEnumLiteralDeclaration_26; }

		//"Mcircle"
		public Keyword getMcircleMcircleKeyword_26_0() { return cMcircleMcircleKeyword_26_0; }

		//rect
		public EnumLiteralDeclaration getRectEnumLiteralDeclaration_27() { return cRectEnumLiteralDeclaration_27; }

		//"rect"
		public Keyword getRectRectKeyword_27_0() { return cRectRectKeyword_27_0; }

		//rectangle
		public EnumLiteralDeclaration getRectangleEnumLiteralDeclaration_28() { return cRectangleEnumLiteralDeclaration_28; }

		//"rectangle"
		public Keyword getRectangleRectangleKeyword_28_0() { return cRectangleRectangleKeyword_28_0; }

		//square
		public EnumLiteralDeclaration getSquareEnumLiteralDeclaration_29() { return cSquareEnumLiteralDeclaration_29; }

		//"square"
		public Keyword getSquareSquareKeyword_29_0() { return cSquareSquareKeyword_29_0; }

		//star
		public EnumLiteralDeclaration getStarEnumLiteralDeclaration_30() { return cStarEnumLiteralDeclaration_30; }

		//"star"
		public Keyword getStarStarKeyword_30_0() { return cStarStarKeyword_30_0; }

		//none
		public EnumLiteralDeclaration getNoneEnumLiteralDeclaration_31() { return cNoneEnumLiteralDeclaration_31; }

		//"none"
		public Keyword getNoneNoneKeyword_31_0() { return cNoneNoneKeyword_31_0; }

		//underline
		public EnumLiteralDeclaration getUnderlineEnumLiteralDeclaration_32() { return cUnderlineEnumLiteralDeclaration_32; }

		//"underline"
		public Keyword getUnderlineUnderlineKeyword_32_0() { return cUnderlineUnderlineKeyword_32_0; }

		//cylinder
		public EnumLiteralDeclaration getCylinderEnumLiteralDeclaration_33() { return cCylinderEnumLiteralDeclaration_33; }

		//"cylinder"
		public Keyword getCylinderCylinderKeyword_33_0() { return cCylinderCylinderKeyword_33_0; }

		//note
		public EnumLiteralDeclaration getNoteEnumLiteralDeclaration_34() { return cNoteEnumLiteralDeclaration_34; }

		//"note"
		public Keyword getNoteNoteKeyword_34_0() { return cNoteNoteKeyword_34_0; }

		//tab
		public EnumLiteralDeclaration getTabEnumLiteralDeclaration_35() { return cTabEnumLiteralDeclaration_35; }

		//"tab"
		public Keyword getTabTabKeyword_35_0() { return cTabTabKeyword_35_0; }

		//folder
		public EnumLiteralDeclaration getFolderEnumLiteralDeclaration_36() { return cFolderEnumLiteralDeclaration_36; }

		//"folder"
		public Keyword getFolderFolderKeyword_36_0() { return cFolderFolderKeyword_36_0; }

		//box3d
		public EnumLiteralDeclaration getBox3dEnumLiteralDeclaration_37() { return cBox3dEnumLiteralDeclaration_37; }

		//"box3d"
		public Keyword getBox3dBox3dKeyword_37_0() { return cBox3dBox3dKeyword_37_0; }

		//component
		public EnumLiteralDeclaration getComponentEnumLiteralDeclaration_38() { return cComponentEnumLiteralDeclaration_38; }

		//"component"
		public Keyword getComponentComponentKeyword_38_0() { return cComponentComponentKeyword_38_0; }

		//promoter
		public EnumLiteralDeclaration getPromoterEnumLiteralDeclaration_39() { return cPromoterEnumLiteralDeclaration_39; }

		//"promoter"
		public Keyword getPromoterPromoterKeyword_39_0() { return cPromoterPromoterKeyword_39_0; }

		//cds
		public EnumLiteralDeclaration getCdsEnumLiteralDeclaration_40() { return cCdsEnumLiteralDeclaration_40; }

		//"cds"
		public Keyword getCdsCdsKeyword_40_0() { return cCdsCdsKeyword_40_0; }

		//terminator
		public EnumLiteralDeclaration getTerminatorEnumLiteralDeclaration_41() { return cTerminatorEnumLiteralDeclaration_41; }

		//"terminator"
		public Keyword getTerminatorTerminatorKeyword_41_0() { return cTerminatorTerminatorKeyword_41_0; }

		//utr
		public EnumLiteralDeclaration getUtrEnumLiteralDeclaration_42() { return cUtrEnumLiteralDeclaration_42; }

		//"utr"
		public Keyword getUtrUtrKeyword_42_0() { return cUtrUtrKeyword_42_0; }

		//primersite
		public EnumLiteralDeclaration getPrimersiteEnumLiteralDeclaration_43() { return cPrimersiteEnumLiteralDeclaration_43; }

		//"primersite"
		public Keyword getPrimersitePrimersiteKeyword_43_0() { return cPrimersitePrimersiteKeyword_43_0; }

		//restrictionsite
		public EnumLiteralDeclaration getRestrictionsiteEnumLiteralDeclaration_44() { return cRestrictionsiteEnumLiteralDeclaration_44; }

		//"restrictionsite"
		public Keyword getRestrictionsiteRestrictionsiteKeyword_44_0() { return cRestrictionsiteRestrictionsiteKeyword_44_0; }

		//fivepoverhang
		public EnumLiteralDeclaration getFivepoverhangEnumLiteralDeclaration_45() { return cFivepoverhangEnumLiteralDeclaration_45; }

		//"fivepoverhang"
		public Keyword getFivepoverhangFivepoverhangKeyword_45_0() { return cFivepoverhangFivepoverhangKeyword_45_0; }

		//threepoverhang
		public EnumLiteralDeclaration getThreepoverhangEnumLiteralDeclaration_46() { return cThreepoverhangEnumLiteralDeclaration_46; }

		//"threepoverhang"
		public Keyword getThreepoverhangThreepoverhangKeyword_46_0() { return cThreepoverhangThreepoverhangKeyword_46_0; }

		//noverhang
		public EnumLiteralDeclaration getNoverhangEnumLiteralDeclaration_47() { return cNoverhangEnumLiteralDeclaration_47; }

		//"noverhang"
		public Keyword getNoverhangNoverhangKeyword_47_0() { return cNoverhangNoverhangKeyword_47_0; }

		//assembly
		public EnumLiteralDeclaration getAssemblyEnumLiteralDeclaration_48() { return cAssemblyEnumLiteralDeclaration_48; }

		//"assembly"
		public Keyword getAssemblyAssemblyKeyword_48_0() { return cAssemblyAssemblyKeyword_48_0; }

		//signature
		public EnumLiteralDeclaration getSignatureEnumLiteralDeclaration_49() { return cSignatureEnumLiteralDeclaration_49; }

		//"signature"
		public Keyword getSignatureSignatureKeyword_49_0() { return cSignatureSignatureKeyword_49_0; }

		//insulator
		public EnumLiteralDeclaration getInsulatorEnumLiteralDeclaration_50() { return cInsulatorEnumLiteralDeclaration_50; }

		//"insulator"
		public Keyword getInsulatorInsulatorKeyword_50_0() { return cInsulatorInsulatorKeyword_50_0; }

		//ribosite
		public EnumLiteralDeclaration getRibositeEnumLiteralDeclaration_51() { return cRibositeEnumLiteralDeclaration_51; }

		//"ribosite"
		public Keyword getRibositeRibositeKeyword_51_0() { return cRibositeRibositeKeyword_51_0; }

		//rnastab
		public EnumLiteralDeclaration getRnastabEnumLiteralDeclaration_52() { return cRnastabEnumLiteralDeclaration_52; }

		//"rnastab"
		public Keyword getRnastabRnastabKeyword_52_0() { return cRnastabRnastabKeyword_52_0; }

		//proteasesite
		public EnumLiteralDeclaration getProteasesiteEnumLiteralDeclaration_53() { return cProteasesiteEnumLiteralDeclaration_53; }

		//"proteasesite"
		public Keyword getProteasesiteProteasesiteKeyword_53_0() { return cProteasesiteProteasesiteKeyword_53_0; }

		//proteinstab
		public EnumLiteralDeclaration getProteinstabEnumLiteralDeclaration_54() { return cProteinstabEnumLiteralDeclaration_54; }

		//"proteinstab"
		public Keyword getProteinstabProteinstabKeyword_54_0() { return cProteinstabProteinstabKeyword_54_0; }

		//rpromoter
		public EnumLiteralDeclaration getRpromoterEnumLiteralDeclaration_55() { return cRpromoterEnumLiteralDeclaration_55; }

		//"rpromoter"
		public Keyword getRpromoterRpromoterKeyword_55_0() { return cRpromoterRpromoterKeyword_55_0; }

		//rarrow
		public EnumLiteralDeclaration getRarrowEnumLiteralDeclaration_56() { return cRarrowEnumLiteralDeclaration_56; }

		//"rarrow"
		public Keyword getRarrowRarrowKeyword_56_0() { return cRarrowRarrowKeyword_56_0; }

		//larrow
		public EnumLiteralDeclaration getLarrowEnumLiteralDeclaration_57() { return cLarrowEnumLiteralDeclaration_57; }

		//"larrow"
		public Keyword getLarrowLarrowKeyword_57_0() { return cLarrowLarrowKeyword_57_0; }

		//lpromoter
		public EnumLiteralDeclaration getLpromoterEnumLiteralDeclaration_58() { return cLpromoterEnumLiteralDeclaration_58; }

		//"lpromoter"
		public Keyword getLpromoterLpromoterKeyword_58_0() { return cLpromoterLpromoterKeyword_58_0; }
	}

	public class RecordBasedNodeShapeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "RecordBasedNodeShape");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRecordEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRecordRecordKeyword_0_0 = (Keyword)cRecordEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMrecordEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMrecordMrecordKeyword_1_0 = (Keyword)cMrecordEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum RecordBasedNodeShape:
		//	record | Mrecord;
		public EnumRule getRule() { return rule; }

		//record | Mrecord
		public Alternatives getAlternatives() { return cAlternatives; }

		//record
		public EnumLiteralDeclaration getRecordEnumLiteralDeclaration_0() { return cRecordEnumLiteralDeclaration_0; }

		//"record"
		public Keyword getRecordRecordKeyword_0_0() { return cRecordRecordKeyword_0_0; }

		//Mrecord
		public EnumLiteralDeclaration getMrecordEnumLiteralDeclaration_1() { return cMrecordEnumLiteralDeclaration_1; }

		//"Mrecord"
		public Keyword getMrecordMrecordKeyword_1_0() { return cMrecordMrecordKeyword_1_0; }
	}
	
	private final ShapeElements pShape;
	private final PolygonBasedShapeElements pPolygonBasedShape;
	private final RecordBasedShapeElements pRecordBasedShape;
	private final PolygonBasedNodeShapeElements unknownRulePolygonBasedNodeShape;
	private final RecordBasedNodeShapeElements unknownRuleRecordBasedNodeShape;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DotShapeGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pShape = new ShapeElements();
		this.pPolygonBasedShape = new PolygonBasedShapeElements();
		this.pRecordBasedShape = new RecordBasedShapeElements();
		this.unknownRulePolygonBasedNodeShape = new PolygonBasedNodeShapeElements();
		this.unknownRuleRecordBasedNodeShape = new RecordBasedNodeShapeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.gef.dot.internal.language.DotShape".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Shape:
	//	shape=(PolygonBasedShape | RecordBasedShape);
	public ShapeElements getShapeAccess() {
		return pShape;
	}
	
	public ParserRule getShapeRule() {
		return getShapeAccess().getRule();
	}

	//PolygonBasedShape:
	//	shape=PolygonBasedNodeShape;
	public PolygonBasedShapeElements getPolygonBasedShapeAccess() {
		return pPolygonBasedShape;
	}
	
	public ParserRule getPolygonBasedShapeRule() {
		return getPolygonBasedShapeAccess().getRule();
	}

	//RecordBasedShape:
	//	shape=RecordBasedNodeShape;
	public RecordBasedShapeElements getRecordBasedShapeAccess() {
		return pRecordBasedShape;
	}
	
	public ParserRule getRecordBasedShapeRule() {
		return getRecordBasedShapeAccess().getRule();
	}

	//enum PolygonBasedNodeShape:
	//	box | polygon | ellipse | oval | circle | point | egg | triangle | plaintext | plain | diamond | trapezium |
	//	parallelogram | house | pentagon | hexagon | septagon | octagon | doublecircle | doubleoctagon | tripleoctagon |
	//	invtriangle | invtrapezium | invhouse | Mdiamond | Msquare | Mcircle | rect | rectangle | square | star | none |
	//	underline | cylinder | note | tab | folder | box3d | component | promoter | cds | terminator | utr | primersite |
	//	restrictionsite | fivepoverhang | threepoverhang | noverhang | assembly | signature | insulator | ribosite | rnastab |
	//	proteasesite | proteinstab | rpromoter | rarrow | larrow | lpromoter;
	public PolygonBasedNodeShapeElements getPolygonBasedNodeShapeAccess() {
		return unknownRulePolygonBasedNodeShape;
	}
	
	public EnumRule getPolygonBasedNodeShapeRule() {
		return getPolygonBasedNodeShapeAccess().getRule();
	}

	//enum RecordBasedNodeShape:
	//	record | Mrecord;
	public RecordBasedNodeShapeElements getRecordBasedNodeShapeAccess() {
		return unknownRuleRecordBasedNodeShape;
	}
	
	public EnumRule getRecordBasedNodeShapeRule() {
		return getRecordBasedNodeShapeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
