/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configurator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.Configurator#getResourceURI <em>Resource URI</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.Configurator#getEClassSpec <em>EClass Spec</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getConfigurator()
 * @model
 * @generated
 */
public interface Configurator extends WithFields
{
  /**
   * Returns the value of the '<em><b>Resource URI</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resource URI</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource URI</em>' containment reference.
   * @see #setResourceURI(ConfiguratorResourceURI)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getConfigurator_ResourceURI()
   * @model containment="true"
   * @generated
   */
  ConfiguratorResourceURI getResourceURI();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.Configurator#getResourceURI <em>Resource URI</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource URI</em>' containment reference.
   * @see #getResourceURI()
   * @generated
   */
  void setResourceURI(ConfiguratorResourceURI value);

  /**
   * Returns the value of the '<em><b>EClass Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>EClass Spec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>EClass Spec</em>' containment reference.
   * @see #setEClassSpec(ConfiguratorEClass)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getConfigurator_EClassSpec()
   * @model containment="true"
   * @generated
   */
  ConfiguratorEClass getEClassSpec();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.Configurator#getEClassSpec <em>EClass Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EClass Spec</em>' containment reference.
   * @see #getEClassSpec()
   * @generated
   */
  void setEClassSpec(ConfiguratorEClass value);

} // Configurator
