/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Backgrounds</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getFeatureBackgrounds()
 * @model
 * @generated
 */
public interface FeatureBackgrounds extends WithFeatureAssociatedExpressions
{
} // FeatureBackgrounds
