/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Images</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getImages()
 * @model
 * @generated
 */
public interface Images extends WithExpressions
{
} // Images
