/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Menu Builder</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.MenuBuilder#getMenus <em>Menus</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.MenuBuilder#getEmfMenus <em>Emf Menus</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getMenuBuilder()
 * @model
 * @generated
 */
public interface MenuBuilder extends WithFields
{
  /**
   * Returns the value of the '<em><b>Menus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menus</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menus</em>' containment reference.
   * @see #setMenus(Menus)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getMenuBuilder_Menus()
   * @model containment="true"
   * @generated
   */
  Menus getMenus();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.MenuBuilder#getMenus <em>Menus</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menus</em>' containment reference.
   * @see #getMenus()
   * @generated
   */
  void setMenus(Menus value);

  /**
   * Returns the value of the '<em><b>Emf Menus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Emf Menus</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emf Menus</em>' containment reference.
   * @see #setEmfMenus(EmfMenus)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getMenuBuilder_EmfMenus()
   * @model containment="true"
   * @generated
   */
  EmfMenus getEmfMenus();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.MenuBuilder#getEmfMenus <em>Emf Menus</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emf Menus</em>' containment reference.
   * @see #getEmfMenus()
   * @generated
   */
  void setEmfMenus(EmfMenus value);

} // MenuBuilder
