/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Label Provider</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureTexts <em>Feature Texts</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureImages <em>Feature Images</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureFonts <em>Feature Fonts</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureForegrounds <em>Feature Foregrounds</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureBackgrounds <em>Feature Backgrounds</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getRowFonts <em>Row Fonts</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getRowForegrounds <em>Row Foregrounds</em>}</li>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getRowBackgrounds <em>Row Backgrounds</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider()
 * @model
 * @generated
 */
public interface TableLabelProvider extends WithFields
{
  /**
   * Returns the value of the '<em><b>Feature Texts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature Texts</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Texts</em>' containment reference.
   * @see #setFeatureTexts(FeatureTexts)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_FeatureTexts()
   * @model containment="true"
   * @generated
   */
  FeatureTexts getFeatureTexts();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureTexts <em>Feature Texts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature Texts</em>' containment reference.
   * @see #getFeatureTexts()
   * @generated
   */
  void setFeatureTexts(FeatureTexts value);

  /**
   * Returns the value of the '<em><b>Feature Images</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature Images</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Images</em>' containment reference.
   * @see #setFeatureImages(FeatureImages)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_FeatureImages()
   * @model containment="true"
   * @generated
   */
  FeatureImages getFeatureImages();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureImages <em>Feature Images</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature Images</em>' containment reference.
   * @see #getFeatureImages()
   * @generated
   */
  void setFeatureImages(FeatureImages value);

  /**
   * Returns the value of the '<em><b>Feature Fonts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature Fonts</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Fonts</em>' containment reference.
   * @see #setFeatureFonts(FeatureFonts)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_FeatureFonts()
   * @model containment="true"
   * @generated
   */
  FeatureFonts getFeatureFonts();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureFonts <em>Feature Fonts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature Fonts</em>' containment reference.
   * @see #getFeatureFonts()
   * @generated
   */
  void setFeatureFonts(FeatureFonts value);

  /**
   * Returns the value of the '<em><b>Feature Foregrounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature Foregrounds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Foregrounds</em>' containment reference.
   * @see #setFeatureForegrounds(FeatureForegrounds)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_FeatureForegrounds()
   * @model containment="true"
   * @generated
   */
  FeatureForegrounds getFeatureForegrounds();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureForegrounds <em>Feature Foregrounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature Foregrounds</em>' containment reference.
   * @see #getFeatureForegrounds()
   * @generated
   */
  void setFeatureForegrounds(FeatureForegrounds value);

  /**
   * Returns the value of the '<em><b>Feature Backgrounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature Backgrounds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Backgrounds</em>' containment reference.
   * @see #setFeatureBackgrounds(FeatureBackgrounds)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_FeatureBackgrounds()
   * @model containment="true"
   * @generated
   */
  FeatureBackgrounds getFeatureBackgrounds();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getFeatureBackgrounds <em>Feature Backgrounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature Backgrounds</em>' containment reference.
   * @see #getFeatureBackgrounds()
   * @generated
   */
  void setFeatureBackgrounds(FeatureBackgrounds value);

  /**
   * Returns the value of the '<em><b>Row Fonts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Row Fonts</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row Fonts</em>' containment reference.
   * @see #setRowFonts(RowFonts)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_RowFonts()
   * @model containment="true"
   * @generated
   */
  RowFonts getRowFonts();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getRowFonts <em>Row Fonts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row Fonts</em>' containment reference.
   * @see #getRowFonts()
   * @generated
   */
  void setRowFonts(RowFonts value);

  /**
   * Returns the value of the '<em><b>Row Foregrounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Row Foregrounds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row Foregrounds</em>' containment reference.
   * @see #setRowForegrounds(RowForegrounds)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_RowForegrounds()
   * @model containment="true"
   * @generated
   */
  RowForegrounds getRowForegrounds();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getRowForegrounds <em>Row Foregrounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row Foregrounds</em>' containment reference.
   * @see #getRowForegrounds()
   * @generated
   */
  void setRowForegrounds(RowForegrounds value);

  /**
   * Returns the value of the '<em><b>Row Backgrounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Row Backgrounds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row Backgrounds</em>' containment reference.
   * @see #setRowBackgrounds(RowBackgrounds)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTableLabelProvider_RowBackgrounds()
   * @model containment="true"
   * @generated
   */
  RowBackgrounds getRowBackgrounds();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TableLabelProvider#getRowBackgrounds <em>Row Backgrounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row Backgrounds</em>' containment reference.
   * @see #getRowBackgrounds()
   * @generated
   */
  void setRowBackgrounds(RowBackgrounds value);

} // TableLabelProvider
