/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.parsley.dsl.model.TypeBinding#getTypeToBind <em>Type To Bind</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTypeBinding()
 * @model
 * @generated
 */
public interface TypeBinding extends Binding
{
  /**
   * Returns the value of the '<em><b>Type To Bind</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type To Bind</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type To Bind</em>' containment reference.
   * @see #setTypeToBind(JvmTypeReference)
   * @see org.eclipse.emf.parsley.dsl.model.ModelPackage#getTypeBinding_TypeToBind()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getTypeToBind();

  /**
   * Sets the value of the '{@link org.eclipse.emf.parsley.dsl.model.TypeBinding#getTypeToBind <em>Type To Bind</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type To Bind</em>' containment reference.
   * @see #getTypeToBind()
   * @generated
   */
  void setTypeToBind(JvmTypeReference value);

} // TypeBinding
