/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.parsley.dsl.model.FormFeatureCaptionProvider;
import org.eclipse.emf.parsley.dsl.model.ModelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Form Feature Caption Provider</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FormFeatureCaptionProviderImpl extends AbstractFeatureCaptionProviderWithLabelImpl implements FormFeatureCaptionProvider
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FormFeatureCaptionProviderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.FORM_FEATURE_CAPTION_PROVIDER;
  }

} //FormFeatureCaptionProviderImpl
