/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.model.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.parsley.dsl.model.ModelPackage;
import org.eclipse.emf.parsley.dsl.model.RowForegrounds;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Row Foregrounds</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RowForegroundsImpl extends WithExpressionsImpl implements RowForegrounds
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RowForegroundsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.ROW_FOREGROUNDS;
  }

} //RowForegroundsImpl
