/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.emf.parsley.dsl.parser.antlr.internal.InternalEmfParsleyDslParser;
import org.eclipse.emf.parsley.dsl.services.EmfParsleyDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EmfParsleyDslParser extends AbstractAntlrParser {

	@Inject
	private EmfParsleyDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEmfParsleyDslParser createParser(XtextTokenStream stream) {
		return new InternalEmfParsleyDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EmfParsleyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EmfParsleyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
