/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EmfParsleyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/emf/parsley/dsl/parser/antlr/internal/InternalEmfParsleyDsl.tokens");
	}
}
