
/*
* generated by Xtext
*/
lexer grammar InternalDotRectLexer;


@header {
package org.eclipse.gef.dot.internal.ui.language.contentassist.antlr.lexer;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.Lexer;
}




Comma : ',';



RULE_DOUBLE : '-'? ('.' ('0'..'9')+|('0'..'9')+ ('.' ('0'..'9')*)?);

RULE_WS : (' '|'\t'|'\r'|'\n')+;



