/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DotArrowTypeAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/gef/dot/internal/language/parser/antlr/internal/InternalDotArrowType.tokens");
	}
}
