/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.gef.dot.internal.language.services.DotHtmlLabelGrammarAccess;

public class DotHtmlLabelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DotHtmlLabelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_HTML_COMMENT");
	}
	
	@Override
	protected org.eclipse.gef.dot.internal.language.parser.antlr.internal.InternalDotHtmlLabelParser createParser(XtextTokenStream stream) {
		return new org.eclipse.gef.dot.internal.language.parser.antlr.internal.InternalDotHtmlLabelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "HtmlLabel";
	}
	
	public DotHtmlLabelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DotHtmlLabelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
