/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.gef.dot.internal.language.services.DotPointGrammarAccess;

public class DotPointParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DotPointGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.eclipse.gef.dot.internal.language.parser.antlr.internal.InternalDotPointParser createParser(XtextTokenStream stream) {
		return new org.eclipse.gef.dot.internal.language.parser.antlr.internal.InternalDotPointParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Point";
	}
	
	public DotPointGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DotPointGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
