/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.gef.dot.internal.language.services.DotShapeGrammarAccess;

public class DotShapeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DotShapeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.gef.dot.internal.language.parser.antlr.internal.InternalDotShapeParser createParser(XtextTokenStream stream) {
		return new org.eclipse.gef.dot.internal.language.parser.antlr.internal.InternalDotShapeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Shape";
	}
	
	public DotShapeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DotShapeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
