/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.parsley.dsl.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractEmfParsleyDslScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
